# Generated by Django 2.2.6 on 2019-10-17 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wans', '0003_auto_20191008_0750'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='curriculum',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
