# Generated by Django 2.2.6 on 2019-10-17 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wans', '0004_pedido_curriculum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pedido',
            name='curriculum',
        ),
        migrations.AddField(
            model_name='cliente',
            name='curriculum',
            field=models.TextField(max_length=3000, null=True),
        ),
    ]
