# Generated by Django 2.2.6 on 2019-10-24 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wans', '0005_auto_20191017_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedido',
            name='latitud',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pedido',
            name='longitud',
            field=models.FloatField(default=0.0),
        ),
    ]
